#######################################################################
## Functions that are in early development for eQTL analysis project ##
#######################################################################
## Author: ...
## Last update: ...

